### ISSUE TITLE
Table not exists: article_total_view_stats 

### ISSUE THREAD

**Issue by memduhcagridemir** [ojs/OjsImportBundle#30]
Importing a journal from OJS 2.4.8, I get the following error:

```
An exception occurred while executing 'SELECT total FROM article_total_view_stats WHERE article_id = :id' with params ["58"]:                                                                                                           
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'ojs.article_total_view_stats' doesn't exist
```

I checked with both OJS2.4.3 and OJS2.4.8, neither of them have "article_total_view_stats" table. I guess this table is added to DergiPark later.  

IMHO, this bundle should work with pkp ojs and it should not depend on the changes made in ojs database.

**Comment by utkuaydin** [comment]
> I checked with both OJS2.4.3 and OJS2.4.8, neither of them have "article_total_view_stats" table. I guess this table is added to DergiPark later.

Possibly. It might be a plugin as well.

>  IMHO, this bundle should work with pkp ojs and it should not depend on the changes made in ojs database.

I agree, that was my intention actually.

**Comment by memduhcagridemir** [comment]
I checked DergiPark database there is no "article_total_view_stats" table in DergiPark also. I was not expecting that. :confused: 

Can you share the structure of this table so I can test importing journals? SQL statements would be great also if you can.

**Comment by utkuaydin** [comment]
Huh, the dump that I am using as reference had those tables. Anyway, I already removed those queries and importing a journal to make sure everything works without them. I'll push it soon.

**Comment by memduhcagridemir** [comment]
That's better, 

Thanks :smile:

**Comment by utkuaydin** [comment]
@memduhcagridemir: Commit b71d7a1 should do the trick. I'll be happy to help in case you come across a problem like that again. Thanks.
